name: Kafka to Elasticsearch CI/CD

on:
  push:
    branches:
      - main


jobs:

  prefect-deploy:
    name: Prefect Deploy
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ arm64 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Prefect Deploy
        env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          DOCKER_NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}
          KAFKA_URL: ${{ secrets.KAFKA_URL }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          KAFKA_TOPIC: ${{ secrets.KAFKA_TOPIC }}
        run: |
          pip install -r requirements.txt
          python deploy.py

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Gibhub Actions - post-deploy
          fields: repo,commit,message,author
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
